# Generated by Django 5.0.6 on 2024-07-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0002_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmart',
            name='address',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='foodmart',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmart',
            name='quantity',
            field=models.CharField(default='Unknown', max_length=12),
            preserve_default=False,
        ),
    ]
