# Generated by Django 5.0.6 on 2024-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0003_foodmart_address_foodmart_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmart',
            name='image',
            field=models.ImageField(default='unknown', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodmart',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
