# Generated by Django 5.0.6 on 2024-07-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0004_foodmart_image_alter_foodmart_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmart',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
