# Generated by Django 5.0.6 on 2024-07-27 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0005_alter_foodmart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmart',
            name='image',
        ),
        migrations.AddField(
            model_name='foodmart',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foodmarts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
