# Generated by Django 5.0.6 on 2024-07-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0007_foodmart_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmart',
            name='is_delivered',
        ),
    ]
