# Generated by Django 5.0.6 on 2024-07-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0008_remove_foodmart_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmart',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
